name: lunara-dev-container

services:
  dev-machine:
    build:
      context: .
      dockerfile: Dockerfile
    user: "1000:1000"
    volumes:
      - ..:/home/lunara-developer/lunara
    command: [ "sleep", "infinity" ]